global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Application metrics
  - job_name: 'otel-fiber-demo'
    static_configs:
      - targets: ['otel-fiber-demo:8080']
    scrape_interval: 10s
    metrics_path: /v1/metrics

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 15s

  # Collector internal metrics
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka metrics (if JMX is enabled)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 30s

  # MongoDB metrics (using mongodb_exporter if available)
  # - job_name: 'mongodb'
  #   static_configs:
  #     - targets: ['mongodb-exporter:9216']

  # Redis metrics (using redis_exporter if available)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

# Alertmanager configuration (if needed)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093